version: '3'

services:
  mongodb:
    container_name: bancoDados
    image: mongo:latest
    ports:
      - "27040:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - ./init.mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - rede

  backend:
    container_name: backend
    build:
      context: .
    ports:
      - "8140:8000"
    environment:
      MONGO_URL: "mongodb://admin:admin123@mongodb:27017/ecommerce"
    depends_on:
      - mongodb
    command:
      [
        "sh",
        "-c",
        "npm run seeder && node ./backend/server.js"
      ]
    volumes:
      - ./backend:/app/backend
    networks:
      - rede

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3140:3000"
    command: [ "sh", "-c", "npm start" ]
    volumes:
      - ./frontend:/app/frontend
    networks:
      - rede

networks:
  rede:
