
const MY_ORDER_LIST_REQUEST = 'MY_ORDER_LIST_REQUEST';
const MY_ORDER_LIST_SUCCESS = 'MY_ORDER_LIST_SUCCESS';
const MY_ORDER_LIST_FAIL = 'MY_ORDER_LIST_FAIL';
const CLEAR_ERRORS = 'CLEAR_ERRORS';
const  ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
const  ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
const  ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export { MY_ORDER_LIST_REQUEST, MY_ORDER_LIST_SUCCESS, MY_ORDER_LIST_FAIL, CLEAR_ERRORS, ORDER_DETAILS_REQUEST, ORDER_DETAILS_SUCCESS, ORDER_DETAILS_FAIL};
